version: "3.1"

services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        depends_on:
            - php-fpm
        ports:
            - 8080:80
        volumes:
            - ./:/var/www:rw
        restart: always

    node:
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile
        ports:
            - 80:8080
        depends_on:
            - php-fpm
        volumes:
            - ./vuejs/src:/usr/src/app/src:rw
        restart: always

    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - ./:/var/www:rw
        user: ${UID}:${GID}
        restart: always

    mongodb:
        build:
            context: .
            dockerfile: ./docker/mongodb/Dockerfile
        restart: always